// eslint-disable-file
module.exports = {
  runtime: {
    version: 2,
    _env: "dev",
    _brand: "websitebuilder",
    _brandDisplayName: "WebsiteBuilder",
    _partnerId: 3,
    _brandedUrls: {
      accounts: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/accounts" },
      app_gateway: { api: "https://app-gateway.websitebuilder.latest.wzdev.co" },
      billing: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/billing" },
      blog: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/blog",
        editor: "https://smart-blog.websitebuilder.latest.wzdev.co",
        public_api: "https://blog-viewer-api-latest.mywebsitebuilder.com"
      },
      booking: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/booking",
        public: "https://bookings.websitebuilder.latest.wzdev.co"
      },
      business: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/business" },
      checkout: { checkout: "https://cp-checkout.websitebuilder.latest.wzdev.co" },
      contacts: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/contacts" },
      control_panel: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/control-panel",
        api_login: "https://app-gateway.websitebuilder.latest.wzdev.co/auth",
        login: "https://login.websitebuilder.latest.wzdev.co",
        login_api: "https://app-gateway.websitebuilder.latest.wzdev.co/auth",
        my: "https://my.websitebuilder.latest.wzdev.co",
        preview: "https://preview.websitebuilder.latest.wzdev.co",
        publish: "websitebuilder-site.latest.wzdev.co",
        shell: "https://app.websitebuilder.latest.wzdev.co",
        partner_api: "https://partner-api.latest.builderservices.io"
      },
      email_marketing: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/email-marketing",
        editor: "https://mail.websitebuilder.latest.wzdev.co",
        my: "https://app.websitebuilder.latest.wzdev.co/marketing/dashboard",
        shell: "https://app.websitebuilder.latest.wzdev.co/marketing",
        public_api: "https://view.latest.creativemail.com"
      },
      feature_service: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/featureservice" },
      general: {
        assets: "https://assets.websitebuilder.com",
        help_chat: "https://www.websitebuilder.walsamb0116.hostrehearsal.com/chat",
        help_page: "https://www.websitebuilder.com/help",
        public_url: "https://www.websitebuilder.com"
      },
      image_proxy: { api: "https://images.mywebsitebuilder.com/s/?" },
      logo_maker: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/logos" },
      nps: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/nps" },
      responsive_editor: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/express-editor",
        editor: "https://designer.websitebuilder.latest.wzdev.co",
        preview: "https://preview-express.websitebuilder.latest.wzdev.co",
        publish: "websitebuilder-express.latest.wzdev.co"
      },
      sitebuilder: {
        control_panel: "https://my.websitebuilder.latest.wzdev.co",
        login: "https://login.websitebuilder.latest.wzdev.co"
      },
      sites: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/sites" },
      social_suite: { editor: "https://social-composer.websitebuilder.latest.wzdev.co" },
      store: {
        store_editor: "https://st-edit.websitebuilder.latest.wzdev.co",
        store_onboarding: "https://st-onboarding.websitebuilder.latest.wzdev.co",
        editor: "https://st-edit.latest.mywebsitebuilder.com",
        store_shop: "https://st-shop.latest.mywebsitebuilder.com"
      },
      traditional_editor: { editor: "https://editor.websitebuilder.latest.wzdev.co" },
      two_lines: {
        api: "https://app-gateway.websitebuilder.latest.wzdev.co/twolines",
        subscription_api: "https://app-gateway.websitebuilder.latest.wzdev.co/twolines/subscriptions",
        fos: "https://latest.2lin.es",
        foswww: "https://www.latest.2lin.es",
        incoming_voice_api: "https://twilio-in.latest.2lin.es/voice",
        outgoing_voice_api: "https://twilio-out.latest.2lin.es/voice"
      },
      word_press: { api: "https://app-gateway.websitebuilder.latest.wzdev.co/wordpress" },
      app_market: { api_internal: "https://appmarket-api.sitebuilder.latest.wzdev.co" },
      data_proxy: { api: "https://data-dev.mywebsitebuilder.com" },
      events: { api: "https://app-gateway.latest.mywebsitebuilder.com/events" },
      storage_service: { api: "https://api.latest.storageservice.io" },
      translations: {
        api: "https://tr-api.latest.builderservices.io",
        api_internal: "https://tr-management-api.latest.builderservices.io"
      },
      publishedsites: "websitebuilder-site.latest.wzdev.co"
    },
    _phoneNumbers: {
      paid: { other: "+1 844-211-7882", us: "844-211-7882" },
      priority: { other: "+1 844-945-3371", us: "844-945-3371" }
    },
    _productConfig: {},
    _apiKeys: {
      google_recaptcha: "6LcqiDYUAAAAAFAsaMLYfXHwB1-hzqFxPi5cKwe-",
      google_tag_manager: "GTM-M3V8Z7X",
      impact_radius_campaign_id: "5573",
      impact_radius_lead_action_id: "12509",
      raygun: "NxNpK93YIp+c7DFqIk6BUw=="
    },
    _const: { name: "WebsiteBuilder", product: "builder", partnerId: 3, emailSuffix: "websitebuilder.com" },
    _settings: {
      contactsync: false,
      emailsuffix: "websitebuilder.com",
      formsubmissionsenabled: true,
      publishedsites: "websitebuilder-site.latest.wzdev.co"
    },
    _help: {
      domainexpiry: "https://www.websitebuilder.com/help/article/domain-renewal-and-redemption-explained",
      freessl: "https://www.websitebuilder.com/help/article/free-ssl",
      howtolinkadomain: "https://www.websitebuilder.com/help/article/how-to-link-a-domain",
      learnmorealexa: "http://support.websitebuilder.com/en/kb/article/403/how-to-use-alexa-with-your-website",
      learnmorevat: "https://www.websitebuilder.com/help/article/what-is-value-added-tax-vat",
      "paypal-update": "https://www.websitebuilder.com/help/article/paypal-account-update-explained",
      regularrates: "https://www.websitebuilder.com/help/article/websitebuilder-renewal-rates",
      whois: "https://www.websitebuilder.com/help/article/whois-privacy-information"
    },
    _terms: {
      autorenewal: "https://www.websitebuilder.com/terms/terms-of-service#autoRenewal",
      cancellation: "https://www.websitebuilder.com/terms/terms-of-service#TERMANDTERMINAT",
      moneyback: "https://www.websitebuilder.com/terms/terms-of-service#REFUNDS",
      privacypolicy: "https://www.endurance.com/privacy/privacy",
      terms: "https://www.websitebuilder.com/terms/terms-of-service"
    },
    _assets: { "brand-logo": "https://assets.websitebuilder.com/images/websitebuilder.svg" },
    _app: "app-logo",
    _buildTime: "2020.0519.0903.0",
    _fetchXsrfTokenEndpoint: "/v1.0/session/preauth",
    _fetchXsrfTokenSiteName: "accounts_api",
    _fetchXsrfTokenHeaderName: "X-CSRF-TOKEN",
    _fetchTokenSiteName: "control-panel",
    _enableAppGateway: true,
    _defaultApiName: "logos"
  },
  translations: {
    "compositions.button.facebook.title": "Facebook",
    "compositions.core.error.defaultMessage": "Something went wrong",
    "compositions.core.error.goBackButton": "Go back",
    "compositions.button.google.title": "Google",
    "modules.authentication.authForm.doNotSellMyDataTitleComponent.title":
      'Disclaimer: Endurance International Group does not sell your data to any third party. However, by law, we are required to display this link "Do Not Sell My Data" for customers: ',
    "modules.authentication.authForm.forgotPasswordTitleComponent.title": "Forgot your password?",
    "modules.authentication.authForm.forgotPasswordFormComponent.enterEmail":
      "Please enter your email address and we will send you a link to reset your password.",
    "modules.authentication.authForm.forgotPasswordFormComponent.resetPassword": "Reset password",
    "modules.authentication.authForm.forgotPasswordFormComponent.somethingWentWrong":
      "Oops, something went wrong resetting your password",
    "modules.authentication.authForm.forgotPasswordFormComponent.successMessage":
      "A link to reset your password has been sent. Please check your email.",
    "modules.authentication.authForm.gdprSignUpComponent.title":
      "You also agree to have your personal information transferred and stored in the United States, which is necessary to provide you with the services under our agreement with you.",
    "modules.authentication.authForm.gdprSignUpComponent.ctctTitle":
      "You also agree to have your personal information transferred and stored in the United States, which is necessary for Constant Contact to provide you with the services under our agreement with you.",
    "modules.authentication.authForm.gdprSignUpComponent.acknowledgement1": "Please click here if you",
    "modules.authentication.authForm.gdprSignUpComponent.acknowledgement2": "do not want",
    "modules.authentication.authForm.gdprSignUpComponent.acknowledgement3":
      "to receive emails about our products, services or special offers. (You can always revoke your consent later by using the Safe Unsubscribe link found at the bottom of every email we send to you.)",
    "modules.authentication.authForm.goToCreateAccountComponent.dontHaveAnAccount": "Don't have an account? Sign up",
    "modules.authentication.authForm.goBackToLoginComponent.goBackToLogin": "Go back to log in",
    "modules.authentication.authForm.goToLoginComponent.alreadyHaveAnAccount": "Already have an account? Log in.",
    "modules.authentication.authForm.signInFormComponent.signIn": "Sign in!",
    "modules.authentication.authForm.signInFormComponent.forgotYourPassword": "Forgot your password?",
    "modules.authentication.authForm.signInFormComponent.somethingWentWrong":
      "Oops, something went wrong signing in to your account",
    "modules.authentication.authForm.signInTitleComponent.title": "Log in to your account",
    "modules.authentication.authForm.signUpFormComponent.signUp": "Sign up!",
    "modules.authentication.authForm.signUpFormComponent.termsOfConditions1":
      "By creating an account you agree to {0}'s",
    "modules.authentication.authForm.signUpFormComponent.termsOfConditions2": "and acknowledge receipt of our",
    "modules.authentication.authForm.signUpFormComponent.emailTermsOfCondition": "Email Marketing Terms & conditions",
    "modules.authentication.authForm.signUpFormComponent.builderTermsOfService": "{0} Terms of Service",
    "modules.authentication.authForm.signUpFormComponent.termsOfService": "Terms of Service",
    "modules.authentication.authForm.signUpFormComponent.privacyNotice": "Privacy Notice",
    "modules.authentication.authForm.signUpFormComponent.alreadyHaveAnAccount": "Already have an account? Log in.",
    "modules.authentication.authForm.signUpFormComponent.somethingWentWrong":
      "Oops, something went wrong creating your account",
    "modules.authentication.authForm.signUpTitleComponent.title1": "Awesome Sauce!",
    "modules.authentication.authForm.signUpTitleComponent.title2": "Create a free account to save your work.",
    "modules.authentication.authForm.socialButtonsBothComponent.or": "or",
    "modules.authentication.authForm.socialLoginErrorComponent.NO_EMAIL2":
      "You have no (verified) email address attached to your social login account.",
    "modules.authentication.authForm.socialLoginErrorComponent.GENERIC":
      "Oops...something went wrong with your social login.",
    "modules.authentication.authForm.socialLoginErrorComponent.DISABLED_ACCOUNT":
      "Sorry, it seems your account has either been disabled or deleted.",
    "modules.authentication.authForm.verifyAccountFormComponent.success":
      "Your email address has been successfully verified",
    "modules.authentication.authForm.verifyAccountFormComponent.error": "Oops something went wrong",
    "modules.authentication.authForm.verifyAccountTitleComponent.title": "Account verification",
    "modules.authentication.authForm.schemas.forgotPasswordSchema.emailLabel": "Email",
    "modules.authentication.authForm.schemas.forgotPasswordSchema.emailValidationIsExisty": "You must enter your email",
    "modules.authentication.authForm.schemas.forgotPasswordSchema.emailValidationMinLenght":
      "You must enter your email",
    "modules.authentication.authForm.schemas.forgotPasswordSchema.emailValidationIsEmail": "Invalid email address",
    "modules.authentication.authForm.schemas.signInSchema.emailLabel": "Email",
    "modules.authentication.authForm.schemas.signInSchema.emailValidationIsExisty": "You must enter your email",
    "modules.authentication.authForm.schemas.signInSchema.emailValidationMinLenght": "You must enter your email",
    "modules.authentication.authForm.schemas.signInSchema.emailValidationIsEmail": "Invalid email address",
    "modules.authentication.authForm.schemas.signInSchema.passwordLabel": "Password",
    "modules.authentication.authForm.schemas.signInSchema.passwordValidationIsExisty": "You must enter your Password",
    "modules.authentication.authForm.schemas.signInSchema.passwordValidationMinLenght":
      "Password needs to have 6 or more characters",
    "modules.authentication.authForm.schemas.signUpSchema.firstNameLabel": "First name",
    "modules.authentication.authForm.schemas.signUpSchema.firstNameValidationIsExisty":
      "You must enter your first name",
    "modules.authentication.authForm.schemas.signUpSchema.firstNameValidationMinLenght":
      "You must enter your first name",
    "modules.authentication.authForm.schemas.signUpSchema.firstNameValidationMinLength2":
      "Your first name cannot be less than 2 characters",
    "modules.authentication.authForm.schemas.signUpSchema.firstNameValidationMaxLength80":
      "Your first name cannot be greater than 80 characters",
    "modules.authentication.authForm.schemas.signUpSchema.lastNameLabel": "Last name",
    "modules.authentication.authForm.schemas.signUpSchema.lastNameValidationIsExisty": "You must enter your last name",
    "modules.authentication.authForm.schemas.signUpSchema.lastNameValidationMinLenght": "You must enter your last name",
    "modules.authentication.authForm.schemas.signUpSchema.lastNameValidationMinLength2":
      "Your last name cannot be less than 2 characters",
    "modules.authentication.authForm.schemas.signUpSchema.lastNameValidationMaxLength80":
      "Your last name cannot be greater than 80 characters",
    "modules.authentication.authForm.schemas.signUpSchema.emailLabel": "Email",
    "modules.authentication.authForm.schemas.signUpSchema.emailValidationIsExisty": "You must enter your email",
    "modules.authentication.authForm.schemas.signUpSchema.emailValidationMaxLength50":
      "Your email address cannot be greater than 50 characters",
    "modules.authentication.authForm.schemas.signUpSchema.emailValidationMaxLength80":
      "Your email address cannot be greater than 80 characters",
    "modules.authentication.authForm.schemas.signUpSchema.emailValidationMinLenght": "You must enter your email",
    "modules.authentication.authForm.schemas.signUpSchema.emailValidationIsEmail": "Invalid email address",
    "modules.authentication.authForm.schemas.signUpSchema.passwordLabel": "Password",
    "modules.authentication.authForm.schemas.signUpSchema.passwordValidationIsExisty": "You must enter your Password",
    "modules.authentication.authForm.schemas.signUpSchema.passwordValidationMinLenght":
      "Password needs to have 6 or more characters",
    "core.modals.components.confirmDialog.yes": "Yes",
    "core.modals.components.confirmDialog.no": "No",
    "core.modals.components.confirmDialog.cancel": "Cancel",
    "core.modals.components.confirmDialog.ok": "Ok",
    "core.modals.components.confirmDialog.save": "Save",
    "core.modals.components.confirmDialog.confirm": "Confirm",
    "modules.navigation.siteselector.groupitem.lastEdited": "Last edited: ",
    "modules.navigation.siteselector.groupitem.unpublished": "Unpublished",
    "modules.navigation.siteselector.groupitem.published": "Published",
    "modules.navigation.siteselector.manageSites": "Manage Sites",
    "modules.navigation.siteselector.group.websites": "Websites",
    "helpers.gmbWithCustomFocusNavigation.title.reviewManagement": "Review Management",
    "helpers.gmbWithCustomFocusNavigation.title.businessListing": "Google My Business Listing",
    "helpers.gmbWithCustomFocusNavigation.postReply": "Post Reply",
    "helpers.gmbWithCustomFocusNavigation.kebabMenu.copyReviewLink": "Copy Review Link",
    "helpers.gmbWithCustomFocusNavigation.kebabMenu.flagReview": "Flag Review",
    "helpers.gmbWithCustomFocusNavigation.kebabMenu.deleteYourReply": "Delete Your Reply",
    "core.propertyEditor.fieldIsRequired": "This field is required.",
    "core.propertyEditor.specificFieldIsRequired": "The {0} is required.",
    "core.propertyEditor.fieldIsEmptyOrInvalid": "Enter a valid {fieldName}",
    "core.propertyEditor.readAgreement": "Read the agreement",
    "core.propertyEditor.onlyUniqueColors": "Only unique colors are allowed.",
    "core.propertyEditor.fileUpload.delete": "DELETE",
    "core.propertyEditor.fileUpload.deleteConfirmation": "Are you sure you want to delete",
    "core.propertyEditor.fileUpload.uploadDropZoneText": "Drop your file or",
    "core.propertyEditor.fileUpload.close": "Close",
    "core.propertyEditor.fileUpload.tos": "Terms of service",
    "logomaker.advancedControls": "Advanced controls",
    "logomaker.backToExpressEditor": "Back to site editor",
    "logomaker.controlsTitle": "Logo settings",
    "logomaker.variationTitle": "Variations",
    "logomaker.variationSubtitle": "Not feeling it yet? Here are a some alternatives to choose from.",
    "logomaker.save": "Save",
    "logomaker.saved": "Saved",
    "logomaker.saving": "Saving..",
    "logomaker.replace": "Replace symbol",
    "logomaker.addSymbol": "Add symbol",
    "logomaker.add": "Add",
    "logomaker.theme": "Theme",
    "logomaker.preview": "Preview",
    "logomaker.colorsPopover.title": "Pick your color palette",
    "logomaker.colorsPopover.cancel": "Cancel",
    "logomaker.colorsPopover.loadMore": "Load More",
    "logomaker.deleteLogo.header": "Are you sure you want to delete your logo?",
    "logomaker.deleteLogo.content":
      "You are about to delete your logo. Once deleted you will not be able to undo this action.",
    "logomaker.expresseditor.save": "Upload logo to my site",
    "logomaker.inspirations.site.label": "Site",
    "logomaker.inspirations.instagram.label": "Instagram",
    "logomaker.inspirations.facebook.label": "Facebook",
    "logomaker.inspirations.card.label": "Businesscard",
    "logomaker.inspirations.shirt.label": "T-Shirt",
    "logomaker.inspirations.bag.label": "Totebag",
    "logomaker.inspirations.backpack.label": "Backpack",
    "logomaker.inspirations.beer.label": "Coaster",
    "logomaker.inspirations.cap.label": "Cap",
    "logomaker.inspirations.display.label": "Sign",
    "logomaker.inspirations.mug.label": "Mug",
    "logomaker.inspirations.sticker.label": "Sticker",
    "logomaker.colors.cancel": "Cancel",
    "logomaker.colors.apply": "Apply",
    "logomaker.segments.noSelected.title": "This is your logo",
    "logomaker.segments.noSelected.subtitle": "Click on one of the segments in the right panel to change the logo",
    "logomaker.segments.name.label": "Name",
    "logomaker.segments.name.title": "Change how your brand name looks",
    "logomaker.segments.name.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.name.brandName": "Brand name",
    "logomaker.segments.name.layout": "Layout",
    "logomaker.segments.name.capitalize": "Capitalize",
    "logomaker.segments.name.alignment": "Alignment",
    "logomaker.segments.name.fontStyle": "Font style",
    "logomaker.segments.name.fontSize": "Font size",
    "logomaker.segments.name.letterSpacing": "Letter spacing",
    "logomaker.segments.name.lineHeight": "Line height",
    "logomaker.segments.name.alignHorizontal": "Horizontal",
    "logomaker.segments.name.alignVertical": "Vertical",
    "logomaker.segments.slogan.label": "Slogan",
    "logomaker.segments.slogan.title": "Change your slogan",
    "logomaker.segments.slogan.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.slogan.name": "Slogan (optional)",
    "logomaker.segments.slogan.size": "Font size",
    "logomaker.segments.slogan.spacing": "Letter spacing",
    "logomaker.segments.slogan.lineHeight": "Line height",
    "logomaker.segments.symbol.label": "Symbol",
    "logomaker.segments.symbol.select": "Select your symbol",
    "logomaker.segments.symbol.title": "Change your symbol",
    "logomaker.segments.symbol.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.symbol.symbolBased": "Symbol based",
    "logomaker.segments.symbol.initialBased": "Initials based",
    "logomaker.segments.color.label": "Colors",
    "logomaker.segments.color.header.title": "Logo colors",
    "logomaker.segments.color.header.action": "Explore color themes",
    "logomaker.segments.color.title": "Change the colors",
    "logomaker.segments.color.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.fonts.label": "Fonts",
    "logomaker.segments.fonts.title": "Change the fonts",
    "logomaker.segments.fonts.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.shape.label": "Shape",
    "logomaker.segments.shape.title": "Change the shape",
    "logomaker.segments.shape.subtitle": "Click on the part of your logo you want to change",
    "logomaker.segments.shape.showShape": "Show shape",
    "logomaker.segments.shape.filled": "Filled",
    "logomaker.segments.shape.lineWidth": "Line width",
    "logomaker.previewLogo.colors": "Colors:",
    "logomaker.previewLogo.fonts": "Fonts:",
    "logomaker.duplicateLogo.header": "Duplicate",
    "logomaker.duplicateLogo.content": "Do you want to duplicate this logo?",
    "logomaker.symbolSearch.label": "Search a symbol",
    "logomaker.designerModal.header.success": "Success!",
    "logomaker.designerModal.header.error": "Oops!",
    "logomaker.designerModal.content.success": "Your votes has been sent successfully.",
    "logomaker.designerModal.content.error": "You already guessed it.. something went wrong.",
    "logomaker.deleteModal.header.success": "Success!",
    "logomaker.deleteModal.header.error": "Oops!",
    "logomaker.deleteModal.content.success": "Your votes has been deleted successfully.",
    "logomaker.deleteModal.content.error": "You already guessed it.. something went wrong.",
    "logomaker.colorWarnings.warning2":
      "This color is used for the shape, selecting this color will change the color of the shape to prevent contrast issues",
    "logomaker.colorWarnings.warning3":
      "This color is used in elements on your shape, selecting this color will change the color of the conflicting elements to prevent contrast issues",
    "logomaker.colorWarnings.warning4": "You cannot use this color, because it is the same as the background",
    "myLogos.createLogo": "Create logo",
    "myLogos.myLogos": "Your logos",
    "myLogos.inspiration": "Logo inspiration",
    "myLogos.inspirationSub": "See your logo applied.",
    "myLogos.subtitle": "Overview of your logo and branding",
    "logomakerEditor.saveModal.title": "Do you want to save your latest changes?",
    "logomakerEditor.saveModal.cancel": "Cancel",
    "logomakerEditor.saveModal.yes": "Yes",
    "logomakerEditor.saveModal.no": "No",
    "logomakerEditor.eeModal.title": "Oops!",
    "logomakerEditor.eeModal.ok": "Ok",
    "logomakerEditor.dropdown.supportCenter": "Support Center",
    "logomakerEditor.dropdown.gettingStarted": "Getting started(Tour)",
    "logomakerEditor.dropdown.undo": "Undo",
    "logomakerEditor.dropdown.redo": "Redo",
    "logomakerEditor.actions.preview": "Preview",
    "logomakerEditor.actions.saved": "Saved",
    "logomakerEditor.actions.save": "Save",
    "logomakerEditor.actions.invert": "Invert",
    "logomakerEditor.download": "Download",
    "logomakerEditor.noSymbol": "No symbol found for '{0}'",
    "modules.onboarding.steps.create.header2": "Create a stunning logo for your company",
    "modules.onboarding.steps.create.subtitle2Rebrand":
      "Try our AI-powered logo builder and create a beautiful logo for your business in seconds.",
    "modules.onboarding.steps.create.subtitleMobileRebrand":
      "Try our AI-powered logo builder and create a beautiful logo for your business in seconds.",
    "modules.onboarding.steps.create.brandName": "Brand name",
    "modules.onboarding.steps.create.helperTextFont":
      "On the right you can press the font and the colors that you like the most! Filling in your slogan is optional.",
    "modules.onboarding.steps.create.helperTextSlogan":
      "In the next step you will be able to choose a symbol for your brand as well. Go for it!",
    "modules.onboarding.steps.create.optionalSlogan": "Your slogan is optional.",
    "modules.onboarding.steps.create.explain":
      "Just press the one you like the most! In the next step you will be able to choose a symbol for your brand as well.",
    "modules.onboarding.steps.create.slogan": "Slogan",
    "modules.onboarding.steps.create.optional": "Filling in your {name} is optional",
    "modules.onboarding.steps.variations.header2": "Choose your logo",
    "modules.onboarding.steps.variations.subtitle2":
      "Select one of the logo's on the right. Afterwards you can change any setting you want, to fine-tune your logo.",
    "modules.onboarding.steps.variations.subtitleMobile":
      "Select one of the logo's below. Afterwards you can change any setting you want, to fine-tune your logo.",
    "modules.onboarding.steps.preview.header2": "Tadaa... here's your logo!",
    "modules.onboarding.steps.preview.subtitle2": "You're done, press finish.",
    "modules.onboarding.steps.preview.chosenFonts": "Fonts:",
    "modules.onboarding.footer.previous": "Previous",
    "modules.onboarding.footer.continue": "Continue",
    "modules.onboarding.footer.finish": "Finish",
    "modules.onboarding.containers.logoType.header": "Here are your logo ideas. Choose the one you like",
    "modules.onboarding.containers.logoType.subtitle": "You can always change the layout in the editor later",
    "modules.onboarding.containers.information.header": "Create a stunning logo for your company.",
    "modules.onboarding.containers.information.subtitleRebrand":
      "Try our AI-powered logo builder and create a beautiful logo for your business in seconds.",
    "modules.onboarding.containers.information.cta": "Create logo",
    "modules.onboarding.containers.information.brandName": "Enter your brand name",
    "modules.onboarding.containers.information.slogan": "Enter a slogan (optional)",
    "modules.onboarding.containers.information.error": "Your company name: {brandName} is too short..",
    "modules.onboarding.containers.selection.title": "Choose your logo",
    "modules.onboarding.containers.selection.subtitle":
      "Select one of the logo's below. Afterwards you can change any setting you want to fine tune the logo."
  }
};
